set_property PACKAGE_PIN E3 [get_ports clk]
set_property PACKAGE_PIN P17 [get_ports rst]

set_property PACKAGE_PIN A13 [get_ports {slowerClock[0]}]
set_property PACKAGE_PIN A15 [get_ports {slowerClock[1]}]
set_property PACKAGE_PIN B16 [get_ports {slowerClock[2]}]
set_property PACKAGE_PIN B18 [get_ports {slowerClock[3]}]
set_property PACKAGE_PIN A14 [get_ports {slowerClock[4]}]
set_property PACKAGE_PIN A16 [get_ports {slowerClock[5]}]
set_property PACKAGE_PIN B17 [get_ports {slowerClock[6]}]
set_property PACKAGE_PIN A18 [get_ports {slowerClock[7]}]
set_property SLEW FAST [get_ports {slowerClock[2]}]
set_property SLEW FAST [get_ports {slowerClock[0]}]
set_property SLEW FAST [get_ports {slowerClock[6]}]
set_property SLEW FAST [get_ports {slowerClock[3]}]
set_property SLEW FAST [get_ports {slowerClock[7]}]
set_property SLEW FAST [get_ports {slowerClock[1]}]
set_property SLEW FAST [get_ports {slowerClock[4]}]
set_property SLEW FAST [get_ports {slowerClock[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {slowerClock[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {slowerClock[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {slowerClock[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {slowerClock[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {slowerClock[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports {slowerClock[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {slowerClock[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {slowerClock[5]}]

set_property IOSTANDARD LVCMOS33 [get_ports clk]

